### ISSUE TITLE
JavaScript is not working

### ISSUE THREAD

**Issue by losier** [losier/losier.github.io#1]
My Js file doesn't work if someone knows how to fix it feel free to contribute some of your time I tried looking for help on StackOverflow and GfG, but doesn't find any solution...

**Comment by jahtomini** [comment]
Hey! I'll like to help. What is the desired result you're aiming for?

**Comment by frazie** [comment]
i'd also like to help alongside @jahtomini

**Comment by losier** [comment]
@jahtomini @frazie Thanks for your interest guys I don't know the exact problem but sometimes my typing effect stops working I mean sometimes my index.html folder is unable to read my js folder. if this clicks anything please let me know
Hope I'm able to explain my problem I'll be grateful to you guys...

**Comment by frazie** [comment]
I believe I can help
Can I have it assigned to me?

**Comment by losier** [comment]
Done @frazie
